"""
Report Service — generates PDF, JSON, and CSV investigation reports.
"""
from __future__ import annotations

import csv
import io
import json
import os
import uuid
from datetime import datetime, timezone
from typing import Any

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models import Case, Wallet, Transaction, Report, ReportFormat, User
from app.config import get_settings
from app.core.logging_config import get_logger

logger = get_logger(__name__)
settings = get_settings()


async def _load_report_data(db: AsyncSession, case_id: str) -> dict[str, Any]:
    """Load all relevant data for a case report."""
    case_result = await db.execute(select(Case).where(Case.id == case_id))
    case = case_result.scalar_one_or_none()

    wallets_result = await db.execute(select(Wallet).where(Wallet.case_id == case_id))
    wallets = wallets_result.scalars().all()

    txns_result = await db.execute(select(Transaction).where(Transaction.case_id == case_id))
    transactions = txns_result.scalars().all()

    seed_wallet = next((w for w in wallets if w.is_seed), wallets[0] if wallets else None)
    suspicious_txns = [t for t in transactions if t.is_suspicious]

    # Build highest-risk wallet
    highest_risk = max(wallets, key=lambda w: w.risk_score or 0.0, default=None)

    return {
        "case": case,
        "wallets": wallets,
        "transactions": transactions,
        "seed_wallet": seed_wallet,
        "suspicious_transactions": suspicious_txns,
        "highest_risk_wallet": highest_risk,
        "generated_at": datetime.now(timezone.utc).isoformat(),
    }


async def generate_report(
    db: AsyncSession,
    case_id: str,
    format_str: str,
    user_id: str,
) -> Report:
    """Generate a report in the requested format and persist to DB."""
    data = await _load_report_data(db, case_id)
    fmt = ReportFormat(format_str)
    os.makedirs(settings.report_output_dir, exist_ok=True)

    filename = f"tracex_report_{case_id}_{datetime.now(timezone.utc).strftime('%Y%m%d_%H%M%S')}.{format_str}"
    filepath = os.path.join(settings.report_output_dir, filename)

    if fmt == ReportFormat.JSON:
        content = _build_json_report(data)
        with open(filepath, "w", encoding="utf-8") as f:
            json.dump(content, f, indent=2, default=str)

    elif fmt == ReportFormat.CSV:
        content_str = _build_csv_report(data)
        with open(filepath, "w", encoding="utf-8", newline="") as f:
            f.write(content_str)

    elif fmt == ReportFormat.PDF:
        _build_pdf_report(data, filepath)

    report = Report(
        case_id=case_id,
        format=fmt,
        file_path=filepath,
        generated_by=user_id,
        generated_at=datetime.now(timezone.utc),
        summary_data=_build_json_report(data),
    )
    db.add(report)
    await db.flush()
    await db.refresh(report)
    logger.info("report_generated", case_id=str(case_id), format=format_str, path=filepath)
    return report


def _build_json_report(data: dict) -> dict:
    case = data["case"]
    wallets = data["wallets"]
    transactions = data["transactions"]
    seed = data["seed_wallet"]
    hrw = data["highest_risk_wallet"]

    return {
        "report_metadata": {
            "title": "TRACE-X Investigation Report",
            "subtitle": "SIH26183 — Fraud-Linked Cryptocurrency Exchange Identification",
            "generated_at": data["generated_at"],
            "version": "1.0",
            "disclaimer": (
                "This report is generated by TRACE-X using heuristic analytics on synthetic "
                "blockchain data. All risk scores, VASP attributions, and recommendations are "
                "probabilistic estimates. They do not constitute legal findings."
            ),
        },
        "case_information": {
            "case_id": str(case.id) if case else None,
            "case_number": case.case_number if case else None,
            "title": case.title if case else None,
            "description": case.description if case else None,
            "victim_name": case.victim_name if case else None,
            "reported_amount_usd": case.reported_amount_usd if case else None,
            "status": case.status.value if case and hasattr(case.status, "value") else str(case.status) if case else None,
            "created_at": case.created_at.isoformat() if case else None,
        },
        "suspect_wallet": {
            "address": seed.address if seed else None,
            "chain": seed.chain if seed else None,
            "label": seed.label if seed else None,
            "risk_score": seed.risk_score if seed else None,
            "risk_level": seed.risk_level.value if seed and seed.risk_level and hasattr(seed.risk_level, "value") else None,
        } if seed else {},
        "transaction_summary": {
            "total_transactions": len(transactions),
            "suspicious_transactions": len(data["suspicious_transactions"]),
            "total_wallets": len(wallets),
            "total_volume_usd": sum(t.amount_usd for t in transactions),
            "first_transaction": min((t.timestamp for t in transactions), default=None),
            "last_transaction": max((t.timestamp for t in transactions), default=None),
        },
        "wallets": [
            {
                "address": w.address,
                "type": w.wallet_type.value if hasattr(w.wallet_type, "value") else str(w.wallet_type),
                "label": w.label,
                "risk_score": w.risk_score,
                "risk_level": w.risk_level.value if w.risk_level and hasattr(w.risk_level, "value") else None,
                "transaction_count": w.transaction_count,
                "vasp_attribution": w.vasp_attribution,
            }
            for w in wallets
        ],
        "fund_flow_path": [
            {
                "tx_hash": t.tx_hash,
                "from": t.from_address,
                "to": t.to_address,
                "amount_usd": t.amount_usd,
                "timestamp": t.timestamp.isoformat() if t.timestamp else None,
                "hop": t.hop_number,
                "risk_flags": t.risk_flags or [],
            }
            for t in sorted(transactions, key=lambda x: x.timestamp or datetime.min.replace(tzinfo=timezone.utc))
        ],
        "highest_risk_wallet": {
            "address": hrw.address if hrw else None,
            "risk_score": hrw.risk_score if hrw else None,
            "risk_level": hrw.risk_level.value if hrw and hrw.risk_level and hasattr(hrw.risk_level, "value") else None,
            "risk_metadata": hrw.risk_metadata if hrw else None,
            "vasp_attribution": hrw.vasp_attribution if hrw else None,
        } if hrw else {},
        "recommendations": _build_recommendations(data),
    }


def _build_csv_report(data: dict) -> str:
    output = io.StringIO()
    writer = csv.writer(output)

    writer.writerow(["TRACE-X Investigation Report"])
    writer.writerow(["Generated At", data["generated_at"]])
    writer.writerow([])

    writer.writerow(["WALLET ADDRESS", "TYPE", "LABEL", "RISK SCORE", "RISK LEVEL", "TX COUNT", "VOLUME USD"])
    for w in data["wallets"]:
        writer.writerow([
            w.address,
            w.wallet_type.value if hasattr(w.wallet_type, "value") else str(w.wallet_type),
            w.label or "",
            w.risk_score or "",
            w.risk_level.value if w.risk_level and hasattr(w.risk_level, "value") else "",
            w.transaction_count,
            w.total_sent_usd,
        ])

    writer.writerow([])
    writer.writerow(["TX HASH", "FROM", "TO", "AMOUNT ETH", "AMOUNT USD", "TIMESTAMP", "HOP", "SUSPICIOUS", "FLAGS"])
    for t in sorted(data["transactions"], key=lambda x: x.timestamp or datetime.min.replace(tzinfo=timezone.utc)):
        writer.writerow([
            t.tx_hash,
            t.from_address,
            t.to_address,
            t.amount_eth,
            t.amount_usd,
            t.timestamp.isoformat() if t.timestamp else "",
            t.hop_number or "",
            t.is_suspicious,
            "|".join(t.risk_flags or []),
        ])

    return output.getvalue()


def _build_pdf_report(data: dict, filepath: str) -> None:
    """Generate a professional PDF report using reportlab."""
    try:
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import cm
        from reportlab.platypus import (
            SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
        )
        from reportlab.lib.enums import TA_CENTER, TA_LEFT
    except ImportError:
        logger.error("reportlab_not_installed")
        raise ImportError("reportlab is required for PDF generation. Install: pip install reportlab")

    doc = SimpleDocTemplate(filepath, pagesize=A4, topMargin=1.5*cm, bottomMargin=1.5*cm)
    styles = getSampleStyleSheet()
    story = []

    # ── Palette ─────────────────────────────────────────────────────────────
    PRIMARY = colors.HexColor("#0f172a")
    ACCENT = colors.HexColor("#6366f1")
    DANGER = colors.HexColor("#ef4444")
    WARNING = colors.HexColor("#f59e0b")
    SUCCESS = colors.HexColor("#10b981")
    LIGHT_BG = colors.HexColor("#f8fafc")

    # ── Styles ───────────────────────────────────────────────────────────────
    title_style = ParagraphStyle("Title", fontSize=22, textColor=PRIMARY, spaceAfter=4, alignment=TA_CENTER, fontName="Helvetica-Bold")
    subtitle_style = ParagraphStyle("Subtitle", fontSize=11, textColor=ACCENT, spaceAfter=2, alignment=TA_CENTER, fontName="Helvetica")
    section_style = ParagraphStyle("Section", fontSize=13, textColor=ACCENT, spaceBefore=12, spaceAfter=4, fontName="Helvetica-Bold")
    body_style = ParagraphStyle("Body", fontSize=9, textColor=PRIMARY, spaceAfter=3, fontName="Helvetica", leading=14)
    disclaimer_style = ParagraphStyle("Disclaimer", fontSize=7.5, textColor=colors.grey, spaceAfter=2, fontName="Helvetica-Oblique")

    case = data["case"]
    now_str = data["generated_at"]

    # ── Title Block ──────────────────────────────────────────────────────────
    story.append(Paragraph("TRACE-X", title_style))
    story.append(Paragraph("Cryptocurrency Fraud Investigation Report", subtitle_style))
    story.append(Paragraph(f"SIH26183 | Generated: {now_str[:19]} UTC", disclaimer_style))
    story.append(HRFlowable(width="100%", thickness=2, color=ACCENT))
    story.append(Spacer(1, 0.3*cm))

    # Disclaimer
    story.append(Paragraph(
        "⚠ DISCLAIMER: This report is generated by TRACE-X using heuristic analytics. "
        "Risk scores and VASP attributions are probabilistic estimates, not legal findings. "
        "All demo data is entirely synthetic.",
        disclaimer_style,
    ))
    story.append(Spacer(1, 0.4*cm))

    # ── Case Information ─────────────────────────────────────────────────────
    story.append(Paragraph("Case Information", section_style))
    if case:
        case_data = [
            ["Case Number", case.case_number],
            ["Title", case.title],
            ["Victim Name", case.victim_name or "—"],
            ["Reported Amount", f"${case.reported_amount_usd:,.2f}" if case.reported_amount_usd else "—"],
            ["Status", case.status.value if hasattr(case.status, "value") else str(case.status)],
            ["Created", case.created_at.strftime("%Y-%m-%d %H:%M UTC") if case.created_at else "—"],
        ]
        t = Table(case_data, colWidths=[5*cm, 12*cm])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (0, -1), LIGHT_BG),
            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.lightgrey),
            ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.white, LIGHT_BG]),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        story.append(t)

    story.append(Spacer(1, 0.4*cm))

    # ── Transaction Summary ──────────────────────────────────────────────────
    story.append(Paragraph("Transaction Summary", section_style))
    txns = data["transactions"]
    total_vol = sum(t.amount_usd for t in txns)
    sus_count = len(data["suspicious_transactions"])

    summary_data = [
        ["Total Transactions", str(len(txns))],
        ["Suspicious Transactions", str(sus_count)],
        ["Total Wallets Traced", str(len(data["wallets"]))],
        ["Total Volume (USD)", f"${total_vol:,.2f}"],
    ]
    t = Table(summary_data, colWidths=[8*cm, 9*cm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), LIGHT_BG),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.white, LIGHT_BG]),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    story.append(t)
    story.append(Spacer(1, 0.4*cm))

    # ── Wallet Risk Table ────────────────────────────────────────────────────
    story.append(Paragraph("Wallet Risk Overview", section_style))
    wallet_rows = [["Address", "Type", "Risk Score", "Risk Level", "Volume USD"]]
    for w in data["wallets"]:
        score = f"{w.risk_score:.1f}" if w.risk_score else "—"
        level = w.risk_level.value if w.risk_level and hasattr(w.risk_level, "value") else "—"
        wallet_rows.append([
            w.address[:28] + "…" if len(w.address) > 28 else w.address,
            w.wallet_type.value if hasattr(w.wallet_type, "value") else "—",
            score,
            level.upper(),
            f"${w.total_sent_usd:,.2f}",
        ])
    wt = Table(wallet_rows, colWidths=[6.5*cm, 3*cm, 2.5*cm, 2.5*cm, 3*cm])
    wt.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), ACCENT),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ("ROWBACKGROUNDS", (1, 1), (-1, -1), [colors.white, LIGHT_BG]),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ("ALIGN", (2, 1), (3, -1), "CENTER"),
    ]))
    story.append(wt)
    story.append(Spacer(1, 0.4*cm))

    # ── Recommendations ──────────────────────────────────────────────────────
    story.append(Paragraph("Investigation Recommendations", section_style))
    for rec in _build_recommendations(data):
        story.append(Paragraph(f"• {rec}", body_style))

    story.append(Spacer(1, 0.5*cm))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.lightgrey))
    story.append(Spacer(1, 0.2*cm))
    story.append(Paragraph(
        f"Generated by TRACE-X v1.0 | SIH26183 | {now_str[:10]} | "
        "This is a synthetic demonstration report.",
        disclaimer_style,
    ))

    doc.build(story)


def _build_recommendations(data: dict) -> list[str]:
    recs = []
    sus_txns = data["suspicious_transactions"]
    wallets = data["wallets"]
    hrw = data["highest_risk_wallet"]

    if sus_txns:
        recs.append(
            f"Initiate formal investigation on {len(sus_txns)} flagged transaction(s). "
            "Submit preservation requests to relevant exchanges."
        )

    if hrw and hrw.risk_score and hrw.risk_score >= 75:
        recs.append(
            f"Highest-risk wallet ({hrw.address[:20]}…) scored {hrw.risk_score:.1f}/100 (CRITICAL). "
            "Request legal process (court order / MLAT) for account holder information from VASP."
        )

    exchange_wallets = [w for w in wallets if w.wallet_type and w.wallet_type.value == "exchange"]
    if exchange_wallets:
        recs.append(
            f"File Suspicious Transaction Reports (STRs) with FIU-IND for {len(exchange_wallets)} exchange wallet(s) identified."
        )

    recs.extend([
        "Cross-reference fund-flow path with NCRP complaint database for additional victim reports.",
        "Consult SAHYOG portal for coordinated LEA action if inter-state jurisdiction is involved.",
        "Engage CERT-In if technical attribution of phishing infrastructure is required.",
        "Preserve all blockchain transaction hashes as digital evidence per IT Act 2000 S.65B.",
        "Note: All attributions carry uncertainty. Independent forensic corroboration is required before any action.",
    ])

    return recs
